name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'amazoncorretto'
          java-version: '22'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t testjavadocker .
      - name: Publish image to docker hub
        run: docker push testjavadocker:latest


  deploy:
    needs: build
    runs-on: [self-hosted]
    steps:
      - name: pull docker image
        run: docker pull testjavadocker:latest
      - name: Delete old containers
        run: docker rm -f spring-app
      - name: Run docker container
        run: docker run -d -p 8080:8080 --name spring-app testjavadocker

